[project]
name = "push-to-talk"
version = "0.1.0"
description = "A push-to-talk speech-to-text application using OpenAI API for real-time transcription and support active window text insertion."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "keyboard>=0.13.5",
    "openai>=1.97.1",
    "pyaudio>=0.2.14",
    "pywin32>=309",
    "websocket-client>=1.8.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pyinstaller>=6.14.2",
    "python-dotenv>=1.1.1",
    "ruff>=0.12.5",
]
